- name: Create new image and start container
- hosts: all
  become: true

  tasks:
    - block:
        - name: Build New Image
          community.docker.docker_image:
            name: ${{lookup('env', 'DOCKER_NAME')}}
            build:
              path: "${{lookup('env', 'WORK_FOLDER')}}/${{ lookup('env', 'SERVICE_REPO') }}"
              dockerfile: Dockerfile

        - name: Start Container
          community.docker.docker_container:
            name: ${{lookup('env', 'DOCKER_NAME')}}
            image: ${{lookup('env', 'DOCKER_NAME')}}
            state: started
            restart_policy: always
            volumes:
              - ${{ lookup('env', 'DOCKER_VOLUME') }}
            ports:
              - "${{ lookup('env', 'DOCKER_PORTS') }}"
