- hosts: all

- name: Setup Docker if its not installed
  ansible.builtin.import_playbook: install_docker.yaml

- name: Install collections
  ansible.builtin.import_playbook: install_collection.yaml

- name: Pull from Git
  ansible.builtin.import_playbook: pull_changes_from_git.yaml

- name: Remove old Docker Container and Image
  ansible.builtin.import_playbook: remove_old_deployment.yaml

- name: Create New Docker Image and Start Container
  ansible.builtin.import_playbook: create_new_deployment.yaml
