- name: Setup Docker if it's not installed
  hosts: all
  become: true
  import_playbook: install_docker.yaml

- name: Pull from Git and re-create container
  hosts: all
  become: true
  import_playbook: update_container.yaml
