- name: Pull changes from git
- hosts: all
  become: true

  tasks:
    - block:
        - name: Git pull
          ansible.builtin.git:
            repo: "{{ lookup('env', 'REPOSITORY_ADDR') }}"
            dest: "{{ lookup('env', 'SYSTEM_FOLDER') }}/{{ lookup('env', 'SERVICE_REPO') }}"
            clone: false
            update: true

      rescue:
        - name: Handle failure when pulling Git repository
          debug:
            msg: "Git pull failed. Check the repository URL and credentials."
