- name: Remove old container and image
- hosts: all
  become: true

  tasks:
    - block:
        - name: Remove Current Container
          community.docker.docker_container:
            name: "${{ lookup('env', 'DOCKER_NAME') }}"
            state: absent

        - name: Remove Current Image
          community.docker.docker_image:
            name: "${{ lookup('env', 'DOCKER_NAME') }}"
            state: absent
