- hosts: all
  become: true

  tasks:
    - block:
        - name: Stop Current Container
          community.docker.docker_container:
            name: ${{lookup('env', 'DOCKER_NAME')}}
            image: ignore
            state: absent

        - name: Remove Current Image
          community.docker.docker_image:
            name: ${{lookup('env', 'DOCKER_NAME')}}
