- hosts: all
  become: true

  tasks:
    - block:
        - name: Check if container is running
          shell: docker ps -a --filter "name={{ lookup('env', 'DOCKER_NAME') }}" --format "{{.Names}}"
          register: container_status
          changed_when: false

        - name: Debug container status
          debug:
            var: container_status.stdout

        - name: Stop Current Container
          community.docker.docker_container:
            name: "${{lookup('env', 'DOCKER_NAME')}}"
            state: stopped

        - name: Remove Current Container
          community.docker.docker_container:
            name: "${{lookup('env', 'DOCKER_NAME')}}"
            state: absent

        - name: Remove Current Image
          community.docker.docker_image:
            name: "${{lookup('env', 'DOCKER_NAME')}}"
            state: absent
