- hosts: all
  become: true

  tasks:
    - block:
        name: Git pull
        git:
          repo: { { github.GITHUB_REPO } }
          dest: ~/dtr_NeuralNewsEditor
          clone: no
          update: yes

  args:
    chdir: ~/dtr_NeuralNewsEditor
