- hosts: all
  become: true

  tasks:
    - block:
        - name: Git pull
          debug:
            msg: "{{ lookup('env', 'SERVICE_REPO') }}"
          git:
            repo: "{{ lookup('env', 'SERVICE_REPO') }}"
            dest: ~/dtr_NeuralNewsEditor
            clone: no
            update: yes
      rescue:
        - name: Handle failure when pulling Git repository
          debug:
            msg: "Git pull failed. Check the repository URL and credentials."
