- hosts: all
  become: true

  tasks:
    - block:
        name: Git pull
        git:
          repo: "{{ lookup('env', 'SERVICE_REPO') }}"
          dest: ~/dtr_NeuralNewsEditor
          clone: no
          update: yes

  args:
    chdir: ~/dtr_NeuralNewsEditor
