- hosts: all
  become: true

  tasks:
    - block:
        - name: Git pull
          git:
            repo: "{{ lookup('env', 'REPOSITORY_ADDR') }}"
            dest: /home/ubuntu/dtr_NeuralNewsEditor
            clone: no
            update: yes
          environment:
            GIT_TRACE: 1
            GIT_CURL_VERBOSE: 1
      rescue:
        - name: Handle failure when pulling Git repository
          debug:
            msg: "Git pull failed. Check the repository URL and credentials. {{ lookup('env', 'REPOSITORY_ADDR') }}"
