- hosts: all
  become: true

  tasks:
    - block:
        - name: Git pull
          git:
            repo: "{{ lookup('env', 'REPOSITORY_ADDR' ) }}"
            dest: ~/dtr_NeuralNewsEditor
            clone: no
            update: yes
      rescue:
        - name: Handle failure when pulling Git repository
          debug:
            msg: "Git pull failed. Check the repository URL and credentials. {{ lookup('env', 'REPOSITORY_ADDR') }}"
