name: ansible via merge event

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [merge_event]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install Ansible
        run: |
          sudo apt install -y ansible

      - name: Create ssh key
        run: |
          echo "${{ secrets.SERVER_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      - name: Ping
        run: |
         ansible all -i "${{secrets.SERVER_ADDR}}" --private-key private_key.pem -m ping
         
      - name: Clean up
        run: rm -f private_key.pem
