name: ansible via merge event

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [merge_event]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install Ansible
        run: |
          sudo apt install -y ansible

      - name: Write server address
        run: |
          echo "${{ secrets.SERVER_ADDR }}" > inventory

      - name: Create ssh key, disable key checking
        run: |
          echo "${{ secrets.SERVER_KEY }}" > private_key
          chmod 600 private_key
          export ANSIBLE_HOST_KEY_CHECKING=False

      - name: Update service
        run: |
          ansible-playbook -i inventory master_playbook.yaml
        env:
          REPOSITORY_ADDR: "https://${{secrets.ACCESS_TOKEN}}@github.com/${{secrets.REPO_USER}}/${{ secrets.SERVICE_REPO }}"
          WORK_FOLDER: ${{secrets.WORK_FOLDER}}
          DOCKER_NAME: ${{secrets.DOCKER_NAME}}
          REPO_NAME: ${{ secrets.SERVICE_REPO }}
          DOCKER_VOLUME: ${{ secrets.DOCKER_VOLUME }}
          DOCKER_PORTS: ${{secrets.DOCKER_PORTS}}

      - name: Clean up
        run: rm -f private_key.pem
